# Physical properties of the arm.
#
#                       <- Place for end effector.
#              link_6
#                |      <- joint_6
#              link_5
#                |      <- joint_5
#              link_4
#                |      <- joint_4
#              link_3
#                |      <- joint_3
#              link_2
#                |      <- joint_2
#              link_1
#                |      <- joint_1
# __________ base_link ___________
#                                   _____________________________
#                          link_3  /    \                   /    \----__
#                                 | (·)  |   link_4        | (·)  |   |_|  link_6 (holder for end effector)
#                                /-\____/ __________________\____/----
#                               /      /                          /\
#                              /      /                           ||
#                    link_2   /      /                          link_5
#                            /      /
#                           /___   /
#                          /    \_/
#                  link_1 || (·) ||
#                         |\____/|
#                 ________|_____ |_
#                 |                |   base_link
#             ____|________________|______
#
base_link:
  inertial:
    origin:
      dx: -4.6941E-06
      dy: 0.054174
      dz: 0.038824
      dr: 0.0
      dp: 0.0
      dY: 0.0
    mass: 0.7102
    inertia:
      ixx: 0.0039943
      ixy: 3.697E-07
      ixz: -5.7364E-08
      iyy: 0.0014946
      iyz: -0.00036051
      izz: 0.0042554
  visual:
    origin:
      dx: 0.0
      dy: 0.0
      dz: 0.0
      dr: 0.0
      dp: 0.0
      dY: 1.5708
  collision:
    origin:
      dx: 0.0
      dy: 0.0
      dz: 0.0
      dr: 0.0
      dp: 0.0
      dY: 1.5708

link_1:
  inertial:
    origin:
      dx: -0.022706
      dy: 0.04294
      dz: -0.12205
      dr: 0.0
      dp: 0.0
      dY: 0.0
    mass: 0.88065
    inertia:
      ixx: 0.0034
      ixy: 0.00042296
      ixz: -0.00089231
      iyy: 0.0041778
      iyz: 0.0010848
      izz: 0.0027077
  visual:
    origin:
      dx: 0.0
      dy: 0.0
      dz: 0.0
      dr: 3.1415
      dp: 0.0
      dY: 1.5708
  collision:
    origin:
      dx: 0.0
      dy: 0.0
      dz: 0.0
      dr: 3.1415
      dp: 0.0
      dY: 1.5708

link_2:
  inertial:
    origin:
      dx: 0.064818
      dy: -0.11189
      dz: -0.038671
      dr: 0.0
      dp: 0.0
      dY: 0.0
    mass: 0.57738
    inertia:
      ixx: 0.0047312
      ixy: 0.0022624
      ixz: 0.00032144
      iyy: 0.0020836
      iyz: -0.00056569
      izz: 0.0056129
  visual:
    origin:
      dx: 0.0
      dy: 0.0
      dz: 0.0
      dr: 0.0
      dp: 3.1415
      dY: 0.0
  collision:
    origin:
      dx: 0.0
      dy: 0.0
      dz: 0.0
      dr: 0.0
      dp: 3.1415
      dY: 0.0

link_3:
  inertial:
    origin:
      dx: -0.00029765
      dy: -0.023661
      dz: -0.0019125
      dr: 0.0
      dp: 0.0
      dY: 0.0
    mass: 0.1787
    inertia:
      ixx: 0.0001685
      ixy: -2.7713E-05
      ixz: 5.6885E-06
      iyy: 0.00012865
      iyz: 2.9256E-05
      izz: 0.00020744
  visual:
    origin:
      dx: 0.0
      dy: 0.0
      dz: 0.0
      dr: 3.1415
      dp: 0.0
      dY: 1.5708
  collision:
    origin:
      dx: 0.0
      dy: 0.0
      dz: 0.0
      dr: 3.1415
      dp: 0.0
      dY: 1.5708

link_4:
  inertial:
    origin:
      dx: -0.0016798
      dy: 0.00057319
      dz: -0.074404
      dr: 0.0
      dp: 0.0
      dY: 0.0
    mass: 0.34936
    inertia:
      ixx: 0.0030532
      ixy: -1.8615E-05
      ixz: -7.0047E-05
      iyy: 0.0031033
      iyz: 2.3301E-05
      izz: 0.00022264
  visual:
    origin:
      dx: 0.0
      dy: 0.0
      dz: 0.0
      dr: 0.0
      dp: 3.1415
      dY: 0.0
  collision:
    origin:
      dx: 0.0
      dy: 0.0
      dz: 0.0
      dr: 0.0
      dp: 3.1415
      dY: 0.0

link_5:
  inertial:
    origin:
      dx: 0.0015066
      dy: -1.3102E-05
      dz: -0.012585
      dr: 0.0
      dp: 0.0
      dY: 0.0
    mass: 0.11562
    inertia:
      ixx: 5.5035E-05
      ixy: -1.019E-08
      ixz: -2.6243E-06
      iyy: 8.2921E-05
      iyz: 1.4437E-08
      izz: 5.2518E-05
  visual:
    origin:
      dx: 0.0
      dy: 0.0
      dz: 0.0
      dr: 0.0
      dp: -1.5708
      dY: 0.0
  collision:
    origin:
      dx: 0.0
      dy: 0.0
      dz: 0.0
      dr: 0.0
      dp: -1.5708
      dY: 0.0

link_6:
  inertial:
    origin:
      dx: 2.9287E-10
      dy: -1.6472E-09
      dz: 0.0091432
      dr: 0.0
      dp: 0.0
      dY: 0.0
    mass: 0.013863
    inertia:
      ixx: 1.3596E-06
      ixy: 3.0585E-13
      ixz: 5.7102E-14
      iyy: 1.7157E-06
      iyz: 6.3369E-09
      izz: 2.4332E-06
  visual:
    origin:
      dx: 0.0
      dy: 0.0
      dz: 0.0
      dr: 0.0
      dp: 0.0
      dY: 0.0
  collision:
    origin:
      dx: 0.0
      dy: 0.0
      dz: 0.0
      dr: 0.0
      dp: 0.0
      dY: 0.0
