controller_manager:
  ros__parameters:
    update_rate: 100 # Hz

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    # gripper_controller:
    #   type: position_controllers/GripperActionController

    gripper_controller:
      type: joint_trajectory_controller/GripperActionController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.02
      goal_time: 0.0
      joint_1: { trajectory: 0.3, goal: 0.03 }
      joint_2: { trajectory: 0.3, goal: 0.03 }
      joint_3: { trajectory: 0.3, goal: 0.03 }
      joint_4: { trajectory: 0.3, goal: 0.03 }
      joint_5: { trajectory: 0.3, goal: 0.03 }
      joint_6: { trajectory: 0.3, goal: 0.03 }

# gripper_controller:
#   ros__parameters:
#     joint: gripper_jaw1_joint

gripper_controller:
  ros__parameters:
    joints:
      - gripper_jaw1_joint
